<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JortPob\JortPob.csproj" />
  </ItemGroup>

  <!-- IronPython has to be added as a project reference or it gets cranky -->
  <ItemGroup>
    <Reference Include="IronPython">
      <HintPath>..\JortPob\DLL\IronPython.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.Modules">
      <HintPath>..\JortPob\DLL\IronPython.Modules.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.SQLite">
      <HintPath>..\JortPob\DLL\IronPython.SQLite.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.Wpf">
      <HintPath>..\JortPob\DLL\IronPython.Wpf.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- DLLs -->
  <Target Name="CopyFileToRoot" AfterTargets="AfterBuild">
	<Copy SourceFiles="..\JortPob\DLL\BouncyCastle.Cryptography.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\DrSwizzler.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\ERNavmeshGen.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\ERNavmeshGenCS.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\ESDLang.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\esdtool.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\HKLib.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\HKLib.Reflection.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\HKLib.Serialization.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\HkxUpgradeLib.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\keystone.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\libzstd.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\Microsoft.Dynamic.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\Microsoft.Scripting.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\Microsoft.Scripting.Metadata.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\Mono.Unix.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\NativeFileDialogSharp.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\Newtonsoft.Json.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\nfd.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\SoulsAssetPipeline.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\SoulsFormats.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\SoulsIds.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\StudioUtils.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\System.CodeDom.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\tes3-interop.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\tes3.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\Tommy.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\WitchyFormats.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\ZstdNet.dll" DestinationFolder="$(OutDir)" />
	<Copy SourceFiles="..\JortPob\DLL\Zydis.dll" DestinationFolder="$(OutDir)" />
	  <Copy SourceFiles="..\JortPob\DLL\flite_wrapper.dll" DestinationFolder="$(OutDir)" />
  </Target>

</Project>
