<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>library</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DirectXTexNet" Version="1.0.7" />
		<PackageReference Include="gfoidl.Base64" Version="2.0.0" />
		<PackageReference Include="SharpAssimp" Version="6.0.5" />
		<PackageReference Include="System.Drawing.Common" Version="9.0.5" />
		<PackageReference Include="System.Speech" Version="9.0.9" />
		<PackageReference Include="TeximpNet" Version="1.4.3" />
		<PackageReference Include="XbrzSharp" Version="1.1.0" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ESDLang">
			<HintPath>DLL\ESDLang.dll</HintPath>
		</Reference>
		<Reference Include="esdtool">
			<HintPath>DLL\esdtool.dll</HintPath>
		</Reference>
		<Reference Include="HKLib">
			<HintPath>DLL\HKLib.dll</HintPath>
		</Reference>
		<Reference Include="HKLib.Reflection">
			<HintPath>DLL\HKLib.Reflection.dll</HintPath>
		</Reference>
		<Reference Include="HKLib.Serialization">
			<HintPath>DLL\HKLib.Serialization.dll</HintPath>
		</Reference>
		<Reference Include="HkxUpgradeLib">
			<HintPath>DLL\HkxUpgradeLib.dll</HintPath>
		</Reference>
		<Reference Include="IronPython">
			<HintPath>DLL\IronPython.dll</HintPath>
		</Reference>
		<Reference Include="IronPython.Modules">
			<HintPath>DLL\IronPython.Modules.dll</HintPath>
			<Private></Private>
		</Reference>
		<Reference Include="IronPython.SQLite">
			<HintPath>DLL\IronPython.SQLite.dll</HintPath>
		</Reference>
		<Reference Include="IronPython.Wpf">
			<HintPath>DLL\IronPython.Wpf.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.Dynamic">
			<HintPath>DLL\Microsoft.Dynamic.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.Scripting">
			<HintPath>DLL\Microsoft.Scripting.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.Scripting.Metadata">
			<HintPath>DLL\Microsoft.Scripting.Metadata.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>DLL\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="SoulsAssetPipeline">
			<HintPath>DLL\SoulsAssetPipeline.dll</HintPath>
		</Reference>
		<Reference Include="SoulsFormats">
			<HintPath>DLL\SoulsFormats.dll</HintPath>
		</Reference>
		<Reference Include="SoulsIds">
			<HintPath>DLL\SoulsIds.dll</HintPath>
		</Reference>
		<Reference Include="StudioUtils">
			<HintPath>DLL\StudioUtils.dll</HintPath>
		</Reference>
		<Reference Include="WitchyFormats">
			<HintPath>DLL\WitchyFormats.dll</HintPath>
		</Reference>
		<Reference Include="ZstdNet">
			<HintPath>DLL\ZstdNet.dll</HintPath>
		</Reference>
	</ItemGroup>

	<!-- DLLs -->
	<ItemGroup>
		<None Update="DLL\HKLib.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="DLL\HKLib.Reflection.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="DLL\HKLib.Serialization.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="DLL\HKX2.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="DLL\SoulsIds.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="libzstd.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="DLL\SoulsAssetPipeline.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="DLL\SoulsFormats.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="DLL\ZstdNet.dll">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="oo2core_6_win64.dll">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<!-- Resources -->
	<ItemGroup>
		<None Update="Resources\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="settings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>