<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DirectXTexNet" />
    <PackageReference Include="FFMpegCore" />
    <PackageReference Include="gfoidl.Base64" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" />
    <PackageReference Include="Mutagen.Bethesda.Core" />
    <PackageReference Include="Mutagen.Bethesda.Kernel" />
    <PackageReference Include="Mutagen.Bethesda.Skyrim" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="SharpAssimp" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Speech" />
    <PackageReference Include="TeximpNet" />
    <PackageReference Include="VGAudio" />
    <PackageReference Include="XbrzSharp" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ERNavmeshGenCS">
      <HintPath>DLL\ERNavmeshGenCS.dll</HintPath>
    </Reference>
    <Reference Include="ESDLang">
      <HintPath>DLL\ESDLang.dll</HintPath>
    </Reference>
    <Reference Include="esdtool">
      <HintPath>DLL\esdtool.dll</HintPath>
    </Reference>
    <Reference Include="HKLib">
      <HintPath>DLL\HKLib.dll</HintPath>
    </Reference>
    <Reference Include="HKLib.Reflection">
      <HintPath>DLL\HKLib.Reflection.dll</HintPath>
    </Reference>
    <Reference Include="HKLib.Serialization">
      <HintPath>DLL\HKLib.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="HkxUpgradeLib">
      <HintPath>DLL\HkxUpgradeLib.dll</HintPath>
    </Reference>
    <Reference Include="IronPython">
      <HintPath>DLL\IronPython.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.Modules">
      <HintPath>DLL\IronPython.Modules.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.SQLite">
      <HintPath>DLL\IronPython.SQLite.dll</HintPath>
    </Reference>
    <Reference Include="IronPython.Wpf">
      <HintPath>DLL\IronPython.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Dynamic">
      <HintPath>DLL\Microsoft.Dynamic.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Scripting">
      <HintPath>DLL\Microsoft.Scripting.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Scripting.Metadata">
      <HintPath>DLL\Microsoft.Scripting.Metadata.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>DLL\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="SoulsAssetPipeline">
      <HintPath>DLL\SoulsAssetPipeline.dll</HintPath>
    </Reference>
    <Reference Include="SoulsFormats">
      <HintPath>DLL\SoulsFormats.dll</HintPath>
    </Reference>
    <Reference Include="SoulsIds">
      <HintPath>DLL\SoulsIds.dll</HintPath>
    </Reference>
    <Reference Include="StudioUtils">
      <HintPath>DLL\StudioUtils.dll</HintPath>
    </Reference>
    <Reference Include="tes3-interop">
      <HintPath>DLL\tes3-interop.dll</HintPath>
    </Reference>
    <Reference Include="WitchyFormats">
      <HintPath>DLL\WitchyFormats.dll</HintPath>
    </Reference>
    <Reference Include="ZstdNet">
      <HintPath>DLL\ZstdNet.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\**">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="CopyFileToRoot" AfterTargets="AfterBuild">
    <Copy SourceFiles="DLL\BouncyCastle.Cryptography.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\DrSwizzler.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\ERNavmeshGen.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\ERNavmeshGenCS.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\ESDLang.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\esdtool.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\HKLib.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\HKLib.Reflection.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\HKLib.Serialization.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\HkxUpgradeLib.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\IronPython.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\IronPython.Modules.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\IronPython.SQLite.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\IronPython.Wpf.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\keystone.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\libzstd.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\Microsoft.Dynamic.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\Microsoft.Scripting.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\Microsoft.Scripting.Metadata.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\Mono.Unix.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\NativeFileDialogSharp.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\Newtonsoft.Json.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\nfd.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\SoulsAssetPipeline.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\SoulsFormats.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\SoulsIds.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\StudioUtils.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\System.CodeDom.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\tes3-interop.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\tes3.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\Tommy.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\WitchyFormats.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\ZstdNet.dll" DestinationFolder="$(OutDir)" />
    <Copy SourceFiles="DLL\Zydis.dll" DestinationFolder="$(OutDir)" />
  </Target>
</Project>